# Generated by Django 5.2 on 2025-04-26 06:36

# This file contains the initial migration for the `pwdchecker` app.
# Migrations are used to create and modify database schema over time.

from django.db import migrations, models


class Migration(migrations.Migration):
    # Defines the operations for this migration.
    # This migration creates the `DisallowedWord` model in the database.

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DisallowedWord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=128, unique=True)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
